server:
  port: 8001

spring:
  application:
    name: interception
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: sudalu929
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

knife4j:
  enable: true
  openapi:
    title: mybatis-plus-自定义sql注入器
    description: mybatis-plus-自定义sql注入器
    email: sudalu929@outlook.com
    concat: lqz
    url: localhost:8001/doc.html
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      user:
        group-name: user
        api-rule: package
        api-rule-resources:
          - com.lqz.controller

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*.xml

